// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL_V_vT2iuxtO8GD4cZm2Cq3bGnNvhLcg',
    appId: '1:402167014063:web:7c5b0c78aa5a5e033faa5a',
    messagingSenderId: '402167014063',
    projectId: 'instagram-clone-42b89',
    authDomain: 'instagram-clone-42b89.firebaseapp.com',
    storageBucket: 'instagram-clone-42b89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxZ-8vaPwkmtK1pITIT_NtjTC-uWPB1UA',
    appId: '1:402167014063:android:5c829e514b8590643faa5a',
    messagingSenderId: '402167014063',
    projectId: 'instagram-clone-42b89',
    storageBucket: 'instagram-clone-42b89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVw8qGygr2LkzPFL8fJ5G2XRgr6DH5CJY',
    appId: '1:402167014063:ios:43c4c8424a0a0ada3faa5a',
    messagingSenderId: '402167014063',
    projectId: 'instagram-clone-42b89',
    storageBucket: 'instagram-clone-42b89.appspot.com',
    iosClientId: '402167014063-gnlf7i2andl22th4680m6hdm19oo88ul.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVw8qGygr2LkzPFL8fJ5G2XRgr6DH5CJY',
    appId: '1:402167014063:ios:8863e1e0ae4ec3193faa5a',
    messagingSenderId: '402167014063',
    projectId: 'instagram-clone-42b89',
    storageBucket: 'instagram-clone-42b89.appspot.com',
    iosClientId: '402167014063-0p9ncj8pdm9633sinbpo9r1jcklqjglb.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter.RunnerTests',
  );
}
